export const ADD_MOVIE_TO_WATCH_LIST = "ADD_TO_WATCH_LIST" ;
export const ADD_MOVIE_TO_WATCHED = "Add_TO_WATCHED";
export const REMOVE_MOVIE_FROM_WATCH_LIST = "REMOVE_FROM_WATCH_LIST" ;
export const REMOVE_MOVIE_FROM_WATCHED = "REMOVE_FROM_WATCHED"
export const MOVE_MOVIE_TO_WATCH_LIST = "MOVE_TO_WATCH_LIST"